/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.65
 * Generated at: 2023-03-19 04:34:18 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.*;

public final class bill_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/connection.jsp", Long.valueOf(1678420197726L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("java.sql");
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;


	if(session.getAttribute("uid")==null){
		response.sendRedirect("index.jsp");
		return;
	}

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

	Class.forName("com.mysql.jdbc.Driver");
	Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/dairy", "root", "");

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("	<head>\r\n");
      out.write("		<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("		<title>Admin</title>\r\n");
      out.write("\r\n");
      out.write("		<link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css\">\r\n");
      out.write("		<link rel=\"stylesheet\" href=\"css/dashboard.css\">\r\n");
      out.write("		<link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css\">\r\n");
      out.write("  		<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.6.3/jquery.min.js\"></script>\r\n");
      out.write("  		<script src=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js\"></script>\r\n");
      out.write("	</head>\r\n");
      out.write("\r\n");
      out.write("	<body>\r\n");
      out.write("		");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "staff-sidebar.jsp", out, false);
      out.write("\r\n");
      out.write("		\r\n");
      out.write("		<div class=\"main\">\r\n");
      out.write("			<h1>Welcome - ");
      out.print(session.getAttribute("uname").toString().toUpperCase());
      out.write("</h1>\r\n");
      out.write("\r\n");

	ResultSet rs = con.createStatement().executeQuery("SELECT AUTO_INCREMENT FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA = 'dairy' AND TABLE_NAME = 'customer_bill';");
	rs.next();
	int id = rs.getInt(1);
	
	rs = con.createStatement().executeQuery("select current_date");
	rs.next();
	String bdate = rs.getString(1);
		
	rs = con.createStatement().executeQuery("select bill_no, bill_date, bill_amt, c_name, cow_qty, buffalo_qty, pay_mode, card_no, card_holder, status from customer_bill, customer where customer_bill.cust_id = customer.c_id");

      out.write("\r\n");
      out.write("			<div class=\"container\">\r\n");
      out.write("				<button type=\"button\" class=\"btn btn-danger btn-sm\" data-toggle=\"modal\" data-target=\"#myModal\">Add Bill</button>\r\n");
      out.write("				<table class=\"table table-hover\">\r\n");
      out.write("	    		<thead>\r\n");
      out.write("		      		<tr>\r\n");
      out.write("		        		<th>Bill No</th>\r\n");
      out.write("			        	<th>Bill Date</th>\r\n");
      out.write("			        	<th>Bill Amount</th>\r\n");
      out.write("			        	<th>Customer</th>\r\n");
      out.write("			        	<th>Cow Qty</th>\r\n");
      out.write("			        	<th>Buffalo Qty</th>\r\n");
      out.write("			        	<th>Pay Mode</th>\r\n");
      out.write("			        	<th>Card No</th>\r\n");
      out.write("			        	<th>Card Holder</th>\r\n");
      out.write("			        	<th>Status</th>\r\n");
      out.write("			      	</tr>\r\n");
      out.write("	    		</thead>\r\n");
      out.write("	    		<tbody>\r\n");
 while(rs.next()) { 
      out.write("	    		\r\n");
      out.write("		      		<tr>\r\n");
      out.write("		        		<td>");
      out.print(rs.getString(1));
      out.write("</td>\r\n");
      out.write("		        		<td>");
      out.print(rs.getString(2));
      out.write("</td>\r\n");
      out.write("		        		<td>");
      out.print(rs.getString(3));
      out.write("</td>\r\n");
      out.write("		        		<td>");
      out.print(rs.getString(4));
      out.write("</td>\r\n");
      out.write("		        		<td>");
      out.print(rs.getString(5));
      out.write("</td>\r\n");
      out.write("		        		<td>");
      out.print(rs.getString(6));
      out.write("</td>\r\n");
      out.write("		        		<td>");
      out.print(rs.getString(7));
      out.write("</td>\r\n");
      out.write("		        		<td>");
      out.print(rs.getString(8));
      out.write("</td>\r\n");
      out.write("		        		<td>");
      out.print(rs.getString(9));
      out.write("</td>\r\n");
      out.write("		        		<td>");
      out.print(rs.getString(10));
      out.write("</td>\r\n");
      out.write("						<td><a href=\"delete-bill.jsp?id=");
      out.print(rs.getInt(1));
      out.write("\" class=\"btn btn-sm btn-danger\" onclick=\"return confirm('Delete?');\">Delete</a></td>\r\n");
      out.write("		      		</tr>\r\n");
 } 
      out.write("		      		\r\n");
      out.write("				</tbody>\r\n");
      out.write("	  			</table>\r\n");
      out.write("			</div>\r\n");
      out.write("			\r\n");
      out.write("<div class=\"modal fade\" id=\"myModal\" role=\"dialog\">\r\n");
      out.write("	<div class=\"modal-dialog\">\r\n");
      out.write("		<div class=\"modal-content\">\r\n");
      out.write("        	<div class=\"modal-header\">\r\n");
      out.write("          		<button type=\"button\" class=\"close\" data-dismiss=\"modal\">&times;</button>\r\n");
      out.write("          		<h4 class=\"modal-title\">Bill Details</h4>\r\n");
      out.write("        	</div>\r\n");
      out.write("	        <div class=\"modal-body\">\r\n");
      out.write("\r\n");
      out.write("				<form method=\"post\" action=\"bill1.jsp\">\r\n");
      out.write("					<div class=\"form-group\">\r\n");
      out.write("				    	<label>Bill No:</label>\r\n");
      out.write("				    	<input type=\"text\" class=\"form-control\" name=\"id\" value=\"");
      out.print(id);
      out.write("\" readOnly>\r\n");
      out.write("				  	</div>\r\n");
      out.write("					<div class=\"form-group\">\r\n");
      out.write("				    	<label>Bill Date:</label>\r\n");
      out.write("				    	<input type=\"text\" class=\"form-control\" name=\"bdate\" value=\"");
      out.print(bdate);
      out.write("\" readOnly>\r\n");
      out.write("				  	</div>\r\n");
      out.write("					<div class=\"form-group\">\r\n");
      out.write("				    	<label>Customer:</label>\r\n");
      out.write("						<select name='cid' class=\"form-control\" required>\r\n");
      out.write("						<option value=''>Select Customer</option>\r\n");
 
	rs = con.createStatement().executeQuery("select * from customer");
	while(rs.next()){

      out.write("\r\n");
      out.write("						<option value='");
      out.print(rs.getInt(1));
      out.write('\'');
      out.write('>');
      out.print(rs.getString(2));
      out.write("</option>\r\n");

	}

      out.write("\r\n");
      out.write("	</select>	\r\n");
      out.write("				  	</div>\r\n");
      out.write("					<div class=\"form-group\">\r\n");
      out.write("				    	<label>Cow Qty:</label>\r\n");
      out.write("				    	<input type=\"number\" min=0 class=\"form-control\" name=\"cqty\" required value=\"0\">\r\n");
      out.write("				  	</div>\r\n");
      out.write("					<div class=\"form-group\">\r\n");
      out.write("				    	<label>Buffalo Qty:</label>\r\n");
      out.write("				    	<input type=\"number\" min=0 class=\"form-control\" name=\"bqty\" required value=\"0\">\r\n");
      out.write("				  	</div>\r\n");
      out.write("				  	<button type=\"submit\" class=\"btn btn-success\" name=\"submit\">Save</button>\r\n");
      out.write("				</form>	        \r\n");
      out.write("	        \r\n");
      out.write("        	</div>\r\n");
      out.write("        	<div class=\"modal-footer\">\r\n");
      out.write("          		<button type=\"button\" class=\"btn btn-success\" data-dismiss=\"modal\">Close</button>\r\n");
      out.write("        	</div>\r\n");
      out.write("      	</div>      \r\n");
      out.write("   	</div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("		</div>		\r\n");
      out.write("	</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
