/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.65
 * Generated at: 2023-03-11 04:41:46 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class dashboard_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<html>\n");
      out.write("	<head>\n");
      out.write("        <title>Dairy management system</title>\n");
      out.write("        <script src=\"https://kit.fontawesome.com/d5e4bd332c.js\" crossorigin=\"anonymous\"></script>\n");
      out.write("        <link rel=\"stylesheet\" href=\"css/bootstrap.css\">\n");
      out.write("        <link rel=\"stylesheet\" href=\"css/style.css\">\n");
      out.write("	</head>\n");
      out.write("    \n");
      out.write("    <body class=\"main-body\">\n");
      out.write("    	<header>\n");
      out.write("        	<div class=\"box-area\">\n");
      out.write("				<a href=\"index.jsp\">\n");
      out.write("              	<img src=\"images/NATURE-ONE-DAIRY-CORPORATE-LOGO-01.png\" alt=\"\" class=\"lg\"></a>\n");
      out.write("              	<span class=\"title\">Dairy Management</span>\n");
      out.write("              	<a href=\"loginpage.jsp\" class=\"login\"><i class=\"fas fa-sign-in-alt\"></i>Login</a>\n");
      out.write("        	</div>\n");
      out.write("		</header>\n");
      out.write("		<div class=\"banner-area\">\n");
      out.write("        	<div class=\"menu\">\n");
      out.write("            	<ul>\n");
      out.write("                	<li><a href=\"index.jsp\"><i class=\"fas fa-home\"></i> Home</a></li>\n");
      out.write("                    <li><a href=\"service.jsp\"><i class=\"fas fa-dolly-flatbed\"></i>Services</a></li>\n");
      out.write("					<li><a href=\"aboutus.jsp\"><i class=\"fas fa-info-circle\"></i>About Us</a></li>\n");
      out.write("                    <li><a href=\"gallery.jsp\"><i class=\"far fa-images\"></i>Gallery</a></li>\n");
      out.write("				</ul>\n");
      out.write("			</div>\n");
      out.write("			<h2>Welcome to farmer friendly and eco-friendly dairy</h2>\n");
      out.write("		</div>\n");
      out.write("		<div class=\"section\" id=\"aboutus\">\n");
      out.write("        	<div class=\"products\">\n");
      out.write("            	<h3> Our Products</h3>\n");
      out.write("                <img src=\"images/products.jpg\" alt=\"image\">\n");
      out.write("                <br>\n");
      out.write("                <p>We provide our customers a wide variety of dairy products from organic milk to butter and cheese</span><P>\n");
      out.write("				<a href=\"#\">Read More</a>\n");
      out.write("			</div>\n");
      out.write("            <div class=\"products\">\n");
      out.write("            	<h3>Our Aim </h3>\n");
      out.write("                <img src=\"images/aim.jpg\">\n");
      out.write("                <br>\n");
      out.write("                <p>To build a <span style=\"color:green\">strong </span><span style=\"color:red\">,healthy </span>and <span style=\"color:blue\">nutritious</span> country by providing an employement to all small-scale farmers <P>\n");
      out.write("                <a href=\"#\">Read More</a>\n");
      out.write("			</div>\n");
      out.write("            <div class=\"products\">\n");
      out.write("            	<h3>Working</h3>\n");
      out.write("                <img src=\"images/working.png\" alt=\"image\">\n");
      out.write("                <br>\n");
      out.write("                <p>Let\"s start<P>\n");
      out.write("                <a href=\"#\">Read More</a>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"foot\">\n");
      out.write("				<footer>\n");
      out.write("                	<div class=\"foot-main\">\n");
      out.write("                    	<div class=\"foot1\">\n");
      out.write("                        	<h3 font> About us</h3>\n");
      out.write("                            <p>A dairy is a business enterprise established for the processing of animal milk.mostly from cows or buffaloes,for human consumption.</p>\n");
      out.write("                            <a href=\"#\">read more</a>\n");
      out.write("                        </div>\n");
      out.write("                        <div class=\"foot2\">\n");
      out.write("                            <h3>Find Us</h3>\n");
      out.write("                            <p>Walhekar Wadi</P>\n");
      out.write("                            <p>Near Vaishnav Devi Temple, Akurdi</p>\n");
      out.write("                            <p>PUNE-411035</p>\n");
      out.write("                            <p>TELEPHONE:93590 30625</p>\n");
      out.write("                        </div>\n");
      out.write("                        <div class=\"foot3\">\n");
      out.write("                            <h3>Contact us</h3>\n");
      out.write("                            <p>Subscribe to get our latest updates and offers.</p>\n");
      out.write("                            <br>\n");
      out.write("                            <form class=\"\" action=\"\" method=\"POST\">\n");
      out.write("                            	<input type=\"email\" name=\"subscribe\"  class=\"emailid\" placeholder=\"Enter Your Email ID\"/>\n");
      out.write("                            	<button type=\"submit\" onclick=href\"www.gmail.com\"><span class=\"maile\">submit</span></button>\n");
      out.write("                            	<p>***Don't worry, we wont spam you!</p>\n");
      out.write("                            </form>\n");
      out.write("                        </div>\n");
      out.write("                        <div class=\"foot4\">\n");
      out.write("                            <h3>Follow Us</h3>\n");
      out.write("                            <ul>\n");
      out.write("                              <li><a href=\"https://www.instagram.com/?hl=en\"><i class=\"fab fa-instagram-square\"></i></a></li>\n");
      out.write("                              <li><a href=\"https://www.bing.com/search?q=facebook&form=ANNTH1&refig=57c3a643f07b4d528577f9477c526b74\"><i class=\"fab fa-facebook-square\"></i></i></a></li>\n");
      out.write("                              <li><a href=\"https://www.bing.com/search?q=twitter&cvid=df49de1cdf96439c8e1c74517c24caca&aqs=edge.0.0l7.4519j0j9&FORM=ANAB01&PC=DCTS\"><i class=\"fab fa-twitter-square\"></i></i></a></li>\n");
      out.write("                            </ul>\n");
      out.write("                        </div>\n");
      out.write("					<//div>\n");
      out.write("				</footer>\n");
      out.write("			</div>\n");
      out.write("		</div>\n");
      out.write("	</body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
