/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.65
 * Generated at: 2023-03-16 04:13:45 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.*;

public final class edit_002dfarmer_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/connection.jsp", Long.valueOf(1678420197726L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("java.sql");
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;


	if(session.getAttribute("uid")==null){
		response.sendRedirect("index.jsp");
		return;
	}

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

	Class.forName("com.mysql.jdbc.Driver");
	Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/dairy", "root", "");

      out.write("\r\n");
      out.write("\r\n");

	ResultSet rs = con.createStatement().executeQuery("select * from farmer where f_id="+request.getParameter("id"));
	rs.next();
	
	if(request.getParameter("submit")!=null){
		int id = Integer.parseInt(request.getParameter("id"));
		String name = request.getParameter("name");
		String gender = request.getParameter("gender");
		String email = request.getParameter("email");
		String phone = request.getParameter("phone");
		String addr = request.getParameter("addr");
		
		PreparedStatement ps = con.prepareStatement("update farmer set f_name=?, f_gender=?, f_email=?, f_phone=?, f_address=? where f_id=?");
		ps.setString(1, name);
		ps.setString(2, gender);
		ps.setString(3, email);
		ps.setString(4, phone);
		ps.setString(5, addr);
		ps.setInt(6, id);
		ps.executeUpdate();
		out.print("<script type='text/javascript'>alert('Farmer updated successfully');location.href = 'farmer.jsp';</script>");		
	}

      out.write("\r\n");
      out.write("	\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("	<head>\r\n");
      out.write("		<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("		<title>Admin</title>\r\n");
      out.write("\r\n");
      out.write("		<link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css\">\r\n");
      out.write("		<link rel=\"stylesheet\" href=\"css/dashboard.css\">\r\n");
      out.write("		<link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css\">\r\n");
      out.write("  		<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.6.3/jquery.min.js\"></script>\r\n");
      out.write("  		<script src=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js\"></script>\r\n");
      out.write("	</head>\r\n");
      out.write("\r\n");
      out.write("	<body>\r\n");
      out.write("		");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "staff-sidebar.jsp", out, false);
      out.write("\r\n");
      out.write("		\r\n");
      out.write("		<div class=\"main\">\r\n");
      out.write("			<h1>Welcome - ");
      out.print(session.getAttribute("uname").toString().toUpperCase());
      out.write("</h1>\r\n");
      out.write("\r\n");
      out.write("				<form method=\"post\">\r\n");
      out.write("					<div class=\"form-group\">\r\n");
      out.write("				    	<label>ID:</label>\r\n");
      out.write("				    	<input type=\"text\" class=\"form-control\" name=\"id\" value=\"");
      out.print(rs.getString(1));
      out.write("\" readOnly>\r\n");
      out.write("				  	</div>\r\n");
      out.write("					<div class=\"form-group\">\r\n");
      out.write("				    	<label>Name:</label>\r\n");
      out.write("				    	<input type=\"text\" class=\"form-control\" name=\"name\" value=\"");
      out.print(rs.getString(2));
      out.write("\" required>\r\n");
      out.write("				  	</div>\r\n");
      out.write("					<div class=\"form-group\">\r\n");
      out.write("				    	<label>Gender:</label>\r\n");
      out.write("				    	<select name=\"gender\" class=\"form-control\" required>\r\n");
      out.write("				    	<option value='");
      out.print(rs.getString(3));
      out.write('\'');
      out.write('>');
      out.print(rs.getString(3));
      out.write("</option>\r\n");
      out.write("				    	<option value=\"\">Gender</option>\r\n");
      out.write("				    	<option value=\"Male\">Male</option>\r\n");
      out.write("				    	<option value=\"Female\">Female</option>\r\n");
      out.write("				    	</select>\r\n");
      out.write("				  	</div>\r\n");
      out.write("					<div class=\"form-group\">\r\n");
      out.write("				    	<label>Address:</label>\r\n");
      out.write("				    	<input type=\"text\" class=\"form-control\" name=\"addr\" value=\"");
      out.print(rs.getString(4));
      out.write("\" required>\r\n");
      out.write("				  	</div>				  	\r\n");
      out.write("					<div class=\"form-group\">\r\n");
      out.write("				    	<label>Phone:</label>\r\n");
      out.write("				    	<input type=\"text\" class=\"form-control\" name=\"phone\" pattern=\"^[6789]\\d{9}$\" value=\"");
      out.print(rs.getString(5));
      out.write("\" required>\r\n");
      out.write("				  	</div>\r\n");
      out.write("					<div class=\"form-group\">\r\n");
      out.write("				    	<label>Email:</label>\r\n");
      out.write("				    	<input type=\"email\" class=\"form-control\" name=\"email\" value=\"");
      out.print(rs.getString(6));
      out.write("\" required>\r\n");
      out.write("				  	</div>\r\n");
      out.write("				  	<button type=\"submit\" class=\"btn btn-success\" name=\"submit\">Update</button>\r\n");
      out.write("				</form>	        \r\n");
      out.write("		</div>		\r\n");
      out.write("	</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
