/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.65
 * Generated at: 2023-03-11 06:00:27 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.*;

public final class sedit_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/header_footer.jsp", Long.valueOf(1678513015935L));
    _jspx_dependants.put("/connection.jsp", Long.valueOf(1678420197726L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("java.sql");
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"en\" dir=\"ltr\">\n");
      out.write("	<head>\n");
      out.write("    	<meta charset=\"utf-8\">\n");
      out.write("		<link rel=\"stylesheet\" href=\"css/all.css\">\n");
      out.write("    <style media=\"screen\">\n");
      out.write("    .header {\n");
      out.write("      position: fixed;\n");
      out.write("      right:0;\n");
      out.write("      top: 0;\n");
      out.write("      width: 100%;\n");
      out.write("      background-color: black;\n");
      out.write("      color: white;\n");
      out.write("      text-align: center;\n");
      out.write("    }\n");
      out.write("    .LOGO{\n");
      out.write("      height: 100px;\n");
      out.write("      width: auto;\n");
      out.write("      float: left;\n");
      out.write("      margin-left: 30px;\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    .list{\n");
      out.write("      float: right;\n");
      out.write("      margin-right: 40px;\n");
      out.write("    }\n");
      out.write("\n");
      out.write("\n");
      out.write("    .list li{\n");
      out.write("      display: inline-block;\n");
      out.write("      margin-right: 30px;\n");
      out.write("      margin-top: 30px;\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    .list li a{\n");
      out.write("      text-decoration: none;\n");
      out.write("      font-size: 20px;\n");
      out.write("      color:white;\n");
      out.write("      font-family: serif;\n");
      out.write("      font-weight: bold;\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    .list li:hover{\n");
      out.write("      border-bottom: 4px solid yellow;\n");
      out.write("      transition: .3s;\n");
      out.write("    }\n");
      out.write("\n");
      out.write("\n");
      out.write("      /* Full-width input fields */\n");
      out.write("      input[type=text], input[type=number], select {\n");
      out.write("        width: 50%;\n");
      out.write("        padding: 12px 20px;\n");
      out.write("        margin: 8px 0;\n");
      out.write("\n");
      out.write("        display: inline-block;\n");
      out.write("        border: 1px solid #ccc;\n");
      out.write("        box-sizing: border-box;\n");
      out.write("      }\n");
      out.write("\n");
      out.write("      /* Set a style for all buttons */\n");
      out.write("      button {\n");
      out.write("        background-color: #04AA6D;\n");
      out.write("        color: white;\n");
      out.write("        padding: 14px 20px;\n");
      out.write("        margin: 8px 8px;\n");
      out.write("        border: none;\n");
      out.write("        cursor: pointer;\n");
      out.write("        width: 50%;\n");
      out.write("      }\n");
      out.write("\n");
      out.write("      button:hover {\n");
      out.write("        opacity: 0.8;\n");
      out.write("      }\n");
      out.write("\n");
      out.write("      /* Extra styles for the cancel button */\n");
      out.write("      .cancelbtn {\n");
      out.write("        width: auto;\n");
      out.write("        padding: 10px 18px;\n");
      out.write("        background-color: #f44336;\n");
      out.write("      }\n");
      out.write("\n");
      out.write("      .submit-btn-add{\n");
      out.write("        margin-left: 140px;\n");
      out.write("        width: auto;\n");
      out.write("        height: 40px;\n");
      out.write("        width: 200px;\n");
      out.write("        background-color:#00ff00;\n");
      out.write("      }\n");
      out.write("\n");
      out.write("      /* Center the image and position the close button */\n");
      out.write("\n");
      out.write("      .container {\n");
      out.write("        padding: 16px;\n");
      out.write("      }\n");
      out.write("\n");
      out.write("\n");
      out.write("      /* The Modal (background) */\n");
      out.write("      .modal {\n");
      out.write("        display: none; /* Hidden by default */\n");
      out.write("        position: fixed; /* Stay in place */\n");
      out.write("        z-index: 1; /* Sit on top */\n");
      out.write("        left: 0;\n");
      out.write("        top: 0;\n");
      out.write("        width: 100%; /* Full width */\n");
      out.write("        height: 100%; /* Full height */\n");
      out.write("        overflow: auto; /* Enable scroll if needed */\n");
      out.write("        background-color: rgb(0,0,0); /* Fallback color */\n");
      out.write("        background-color: rgba(0,0,0,0.4); /* Black w/ opacity */\n");
      out.write("        padding-top: 5px;\n");
      out.write("      }\n");
      out.write("\n");
      out.write("      /* Modal Content/Box */\n");
      out.write("      .modal-content {\n");
      out.write("        background-color: #fefefe;\n");
      out.write("        margin: 1% auto 15% auto; /* 5% from the top, 15% from the bottom and centered */\n");
      out.write("        border: 1px solid #888;\n");
      out.write("        width: 40%; /* Could be more or less, depending on screen size */\n");
      out.write("      }\n");
      out.write("\n");
      out.write("      /* The Close Button (x) */\n");
      out.write("      .close {\n");
      out.write("        position: absolute;\n");
      out.write("        right: 25px;\n");
      out.write("        top: 0;\n");
      out.write("        color: #000;\n");
      out.write("        font-size: 35px;\n");
      out.write("        font-weight: bold;\n");
      out.write("      }\n");
      out.write("\n");
      out.write("      h2{\n");
      out.write("        text-align: center;\n");
      out.write("        font-family:serif;\n");
      out.write("        font-weight: bolder;\n");
      out.write("        color: white;\n");
      out.write("        font-size: 30px;\n");
      out.write("\n");
      out.write("      }\n");
      out.write("      h3{\n");
      out.write("        text-align: center;\n");
      out.write("        font-family:serif;\n");
      out.write("        font-weight: bolder;\n");
      out.write("        color: green;\n");
      out.write("        font-size: 30px;\n");
      out.write("\n");
      out.write("      }\n");
      out.write("      sup{\n");
      out.write("        color: red;\n");
      out.write("      }\n");
      out.write("\n");
      out.write("      label{\n");
      out.write("        display: block;\n");
      out.write("        float: left;\n");
      out.write("        width : 120px;\n");
      out.write("      }\n");
      out.write("\n");
      out.write("      .close:hover,\n");
      out.write("      .close:focus {\n");
      out.write("        color: red;\n");
      out.write("        cursor: pointer;\n");
      out.write("      }\n");
      out.write("\n");
      out.write("      /* Add Zoom Animation */\n");
      out.write("      .animate {\n");
      out.write("        -webkit-animation: animatezoom 0.6s;\n");
      out.write("        animation: animatezoom 0.6s\n");
      out.write("      }\n");
      out.write("\n");
      out.write("      @-webkit-keyframes animatezoom {\n");
      out.write("        from {-webkit-transform: scale(0)}\n");
      out.write("        to {-webkit-transform: scale(1)}\n");
      out.write("      }\n");
      out.write("\n");
      out.write("      @keyframes animatezoom {\n");
      out.write("        from {transform: scale(0)}\n");
      out.write("        to {transform: scale(1)}\n");
      out.write("      }\n");
      out.write("\n");
      out.write("      /* Change styles for span and cancel button on extra small screens */\n");
      out.write("      @media screen and (max-width: 300px) {\n");
      out.write("        .cancelbtn {\n");
      out.write("           width: 100%;\n");
      out.write("        }\n");
      out.write("      }\n");
      out.write("\n");
      out.write("      .main-container{\n");
      out.write("        margin-top: 80px;\n");
      out.write("      }\n");
      out.write("\n");
      out.write("      .h2{\n");
      out.write("        margin-top: 30px;\n");
      out.write("\n");
      out.write("      }\n");
      out.write("\n");
      out.write("    .footer {\n");
      out.write("      position: fixed;\n");
      out.write("      left: 0;\n");
      out.write("      bottom: 0;\n");
      out.write("      width: 100%;\n");
      out.write("      background-color: black;\n");
      out.write("      color:white;\n");
      out.write("      text-align: center;\n");
      out.write("    }\n");
      out.write("</style>\n");
      out.write("\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("	<div class=\"header\">\n");
      out.write("		<a href=\"dashboard.jsp\">  <img src=\"images/NATURE-ONE-DAIRY-CORPORATE-LOGO-01.png\"  alt=\"logo\" class=\"LOGO\"></a>\n");
      out.write("        <ul class=\"list\">\n");
      out.write("        	<li> <a href=\"dashboard.jsp\" class=\"effect\"><i class=\"fas fa-home\"></i>  HOME</a> </li>\n");
      out.write("            <li> <a href=\"service.jsp\" class=\"effect\"> <i class=\"fas fa-dolly-flatbed\"></i> SERVICES</a> </li>\n");
      out.write("            <li> <a href=\"aboutus.jsp\" class=\"effect\"><i class=\"fas fa-info-circle\"></i>  ABOUT US</a> </li>\n");
      out.write("            <li> <a href=\"logout.jsp\" class=\"effect\"><i class='fas fa-sign-out-alt'></i> LOGOUT</a> </li>\n");
      out.write("		</ul>\n");
      out.write("	</div>\n");
      out.write("	<div class=\"footer\">\n");
      out.write("		<p><h4>&copy MyDairy.com ");
      out.print(new java.util.Date().getYear()+1900);
      out.write(" - All Rights Reserved (Developed by Tofik & Shubham)</h4></p>\n");
      out.write("	</div>\n");
      out.write("</body>\n");
      out.write("</html>\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"\" dir=\"ltr\">\n");
      out.write("  <head>\n");
      out.write("    <meta charset=\"utf-8\">\n");
      out.write("    <title>Update Staff</title>\n");
      out.write("    <link rel=\"stylesheet\" href=\"css/all.css\">\n");
      out.write("    <link rel=\"stylesheet\" href=\"css/farmer.css\">\n");
      out.write("    <style media=\"screen\">\n");
      out.write("    .delete-icon {\n");
      out.write("      position: absolute;\n");
      out.write("      padding: 4px 5px;\n");
      out.write("      border-radius: 5px;\n");
      out.write("      text-decoration: none;\n");
      out.write("      margin-left: 50px;\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    .delete-icon:hover {\n");
      out.write("      transform: scale(1.2);\n");
      out.write("      opacity: 0.8;\n");
      out.write("    }\n");
      out.write("    u{\n");
      out.write("      text-decoration: none;\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    </style>\n");
      out.write("        	<script src='https://kit.fontawesome.com/a076d05399.js' crossorigin='anonymous'></script>\n");
      out.write("    \n");
      out.write("  </head>\n");
      out.write("  <body>\n");
      out.write("\n");
      out.write("\r\n");
      out.write("\r\n");

	Class.forName("com.mysql.jdbc.Driver");
	Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/dairy", "root", "");

      out.write('\n');
      out.write('\n');

	String id = request.getParameter("eid");
	ResultSet rs = con.createStatement().executeQuery("select * from employee where eid="+id);
	rs.next();

	if (request.getParameter("updatestaffdata")!=null) {
		String idupdate = request.getParameter("eid");
        String ename  =  request.getParameter("fname");
        String phno =  request.getParameter("phonenumber");
        String salary  =  request.getParameter("salary");
        String designation  =  request.getParameter("Designation");
        String address    =  request.getParameter("staffaddress");
        
        int n = con.createStatement().executeUpdate("UPDATE employee SET eid="+id+",ename='"+ename+"',phno='"+phno+"',address='"+address+"',salary='"+salary+"',designation='"+designation+"' WHERE eid="+idupdate);
		
		if(n>0){
			out.print("<script>alert('Staff record saved successfully!!!');location.href='staff.jsp'</script>");
		}
		else{
			out.print("<script>alert('Someting went wrong!!!');location.href='staff.jsp'</script>");			
		}
	}

      out.write("\n");
      out.write("<br><br><br><br><br>\n");
      out.write("      <form class=\"modal-content animate\" action=\"\" method=\"POST\">\n");
      out.write("      <h3>  <b> <u> Update Staff details</u></b>  <a class=\"delete-icon\" href=\"staff.jsp\">  <i class=\"fas fa-arrow-circle-left\"></i></a></h3>\n");
      out.write("        <div class=\"container\">\n");
      out.write("		        <label for=\"fname\">ID <sup>*</sup> </label>\n");
      out.write("		        <input type=\"text\" name=\"id\" value='");
      out.print(rs.getString("eid"));
      out.write("' readOnly/>\n");
      out.write("		        <br>\n");
      out.write("        		<label for=\"fname\">First Name <sup>*</sup> </label>\n");
      out.write("                <input type=\"text\" name=\"fname\" value='");
      out.print(rs.getString("ename"));
      out.write("' placeholder=\"first name\" required/>\n");
      out.write("                <br>\n");
      out.write("                <label for=\"phonenumber\">Phone number<sup>*</sup> </label>\n");
      out.write("                <input type=\"text\" name=\"phonenumber\" value='");
      out.print(rs.getString("phno"));
      out.write("' placeholder=\"Phone Number\" required/>\n");
      out.write("                <br>\n");
      out.write("                <label for=\"staffaddress\">Address<sup>*</sup> </label>\n");
      out.write("                <input type=\"text\" name=\"staffaddress\" value='");
      out.print(rs.getString("address"));
      out.write("' placeholder=\"address\" required/>\n");
      out.write("                <br>\n");
      out.write("                <label for=\"salary\">Salary<sup>*</sup> </label>\n");
      out.write("                <input type=\"text\" name=\"salary\" value='");
      out.print(rs.getString("salary"));
      out.write("' placeholder=\"salary\" required/>\n");
      out.write("                <br>\n");
      out.write("	            <label for=\"Designation\">Designation<sup>*</sup> </label>\n");
      out.write("	            <select name=\"Designation\" required>\n");
      out.write("	            <option value='");
      out.print(rs.getString("designation"));
      out.write('\'');
      out.write('>');
      out.print(rs.getString("designation").toUpperCase());
      out.write("</option>\n");
      out.write("	            <option value=\"\">Select Designation</option>\n");
      out.write("	            <option value=\"staff\">STAFF</option>\n");
      out.write("	            <option value=\"manager\">MANAGER</option>\n");
      out.write("	            </select>\n");
      out.write("	            <br>\n");
      out.write("                <input type=\"submit\" name=\"updatestaffdata\" class=\"submit-btn-add\" value=\"Update\">\n");
      out.write("        </div>\n");
      out.write("  </body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
