/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.65
 * Generated at: 2023-03-11 06:04:53 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class service_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"en\" dir=\"ltr\">\n");
      out.write("	<head>\n");
      out.write("    	<meta charset=\"utf-8\">\n");
      out.write("    	<title>Services</title>\n");
      out.write("    	<link rel=\"stylesheet\" href=\"css/servicestyle.css\">\n");
      out.write("  	</head>\n");
      out.write("  \n");
      out.write("  	<body>\n");
      out.write("		<div class=\"header\">\n");
      out.write("      		<a href=\"dashboard.jsp\">  <img src=\"images/NATURE-ONE-DAIRY-CORPORATE-LOGO-01.png\"  alt=\"logo\" class=\"LOGO\"></a>\n");
      out.write("      		<ul class=\"list\">\n");
      out.write("        		<li><a href=\"dashboard.jsp\" class=\"effect\">HOME</a> </li>\n");
      out.write("				<li> <a href=\"aboutus.php\" class=\"effect\">ABOUT US</a> </li>\n");
      out.write("				<li> <a href=\"logout.jsp\" class=\"effect\"><i class='fas fa-sign-out-alt'></i> LOGOUT</a> </li>\n");
      out.write("      		</ul>\n");
      out.write("    	</div>\n");
      out.write("\n");
      out.write("		<div class=\"main-body\">\n");
      out.write("			<div class=\"row\">\n");
      out.write("    			<a href=\"farmer.jsp\">\n");
      out.write("	    			<div class=\"column\">\n");
      out.write("	      				<div class=\"card\">\n");
      out.write("	        				<img src=\"images/images.png\" alt=\"customer\" height=\"100px; \">\n");
      out.write("	        				<p id=\"t1\">Farmer</p>\n");
      out.write("						</div>\n");
      out.write("	    			</div>\n");
      out.write("  				</a>\n");
      out.write("				<a href=\"staff.jsp\">\n");
      out.write("    				<div class=\"column\">\n");
      out.write("      					<div class=\"card\">\n");
      out.write("        					<img src=\"images/staff.png\" alt=\"staff\" height=\"100px;\">\n");
      out.write("        					<p id=\"t1\">Staff</p>\n");
      out.write("						</div>\n");
      out.write("    				</div>\n");
      out.write("				</a>\n");
      out.write("				<a href=\"data.jsp\">\n");
      out.write("					<div class=\"column\">\n");
      out.write("				     	<div class=\"card\">\n");
      out.write("				        	<img src=\"images/farmers.jpeg\" alt=\"staff\" height=\"100px;\">\n");
      out.write("				        	<p id=\"t1\">Data</p>\n");
      out.write("				      	</div>\n");
      out.write("				    </div>\n");
      out.write("				 </a>\n");
      out.write("			</div>\n");
      out.write("			<div class=\"row\">\n");
      out.write("				<a href=\"bill.html\">\n");
      out.write("					<div class=\"column\">\n");
      out.write("				    	<div class=\"card\">\n");
      out.write("				     		<img src=\"images/stocks.jpg\" alt=\"stocks\" height=\"100px;\">\n");
      out.write("				        	<p id=\"t1\">Bill</p>\n");
      out.write("				      	</div>\n");
      out.write("				   	</div>			\n");
      out.write("				</a>\n");
      out.write("				<a href=\"Cart.jsp\">\n");
      out.write("				  	<div class=\"column\">\n");
      out.write("				        <div class=\"card\">\n");
      out.write("				          	<img src=\"images/Dairyproducts.png\" alt=\"stocks\" height=\"100px;\">\n");
      out.write("				          	<p id=\"t1\">Dairy Products</p>\n");
      out.write("				        </div>\n");
      out.write("				    </div>\n");
      out.write("				</a>\n");
      out.write("				<a href=\"Animalinfo.jsp\">\n");
      out.write("      				<div class=\"column\">\n");
      out.write("        				<div class=\"card\">\n");
      out.write("          					<img src=\"images/animals.png\" alt=\"stocks\" height=\"100px;\">\n");
      out.write("          					<p id=\"t1\">Animal Info</p>\n");
      out.write("        				</div>\n");
      out.write("      				</div>\n");
      out.write("    			</a>\n");
      out.write("    		</div>\n");
      out.write("		</div>\n");
      out.write("		<div class=\"footer\">\n");
      out.write("			<p><h4>&copy MyDairy.com ");
      out.print(new java.util.Date().getYear()+1900);
      out.write(" - All Rights Reserved (Developed by Tofik & Shubham)</h4></p>\n");
      out.write("    	</div>\n");
      out.write("    </body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
