/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.65
 * Generated at: 2023-03-21 15:58:11 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class staff_002dsidebar_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<div class=\"sidenav\">\r\n");
      out.write("  	<a href=\"staff.jsp\">Staff</a>\r\n");
      out.write("  	<a href=\"farmer.jsp\">Farmer</a>\r\n");
      out.write("  	<a href=\"customer.jsp\">Customer</a>\r\n");
      out.write("  	<a href=\"collection.jsp\">Collection</a>\r\n");
      out.write("  	<a href=\"payment.jsp\">Payment</a>\r\n");
      out.write("  	<a href=\"bill.jsp\">Bill</a>\r\n");
      out.write("  	<a href=\"loan-request.jsp\">Loan Request</a>\r\n");
      out.write("  	<a href=\"view-stock.jsp\">View Stock</a>\r\n");
if(session.getAttribute("desgn").toString().equals("Manager")){
      out.write("  	\r\n");
      out.write("	<a href=\"view-price.jsp\">View Price</a>\r\n");
} 
      out.write("\r\n");
      out.write("  	<button class=\"dropdown-btn\">Report \r\n");
      out.write("    	<i class=\"fa fa-caret-down\"></i>\r\n");
      out.write("  	</button>\r\n");
      out.write("  	<div class=\"dropdown-container\">\r\n");
      out.write("    	<a href=\"daily-collection.jsp\">Daily Collection</a>\r\n");
      out.write("    	<a href=\"daily-bills.jsp\">Daily Bills</a>\r\n");
      out.write("    	<a href=\"staff-list.jsp\">Staff List</a>\r\n");
      out.write("    	<a href=\"farmer-list.jsp\">Farmers List</a>\r\n");
      out.write("		<a href=\"customer-list.jsp\">Customers List</a>\r\n");
      out.write("  	</div>\r\n");
      out.write("  	<a href=\"logout.jsp\">Logout</a>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("	var dropdown = document.getElementsByClassName(\"dropdown-btn\");\r\n");
      out.write("	var i;\r\n");
      out.write("	for (i = 0; i < dropdown.length; i++) {\r\n");
      out.write("		dropdown[i].addEventListener(\"click\", function() {\r\n");
      out.write("			this.classList.toggle(\"active\");\r\n");
      out.write("			var dropdownContent = this.nextElementSibling;\r\n");
      out.write("			if (dropdownContent.style.display === \"block\") {\r\n");
      out.write("				dropdownContent.style.display = \"none\";\r\n");
      out.write("   			} else {\r\n");
      out.write("  				dropdownContent.style.display = \"block\";\r\n");
      out.write("			}\r\n");
      out.write("		});\r\n");
      out.write("	}\r\n");
      out.write("</script>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
